on:
    push:
      branches: [main]
    workflow_dispatch:
  
  permissions:
    contents: write
jobs:
    build_and_test:
        strategy:
            matrix:
                version: ["14","16","18"]
                os: ["ubuntu-latest","windows-latest"]
      runs-on: ${{matrix.os}}
      steps:
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
          node-version: ${{matrix.os}}

        - name: nps deps and test
          run: npm install && npm run test
            